theme: ../node_modules/dashpit-foundation-theme
linklists:
  crushpaper:
    template: crushpaper
    envelope: entries
    source: /crushpaper-backup-2016-07-30-18-09-38.json
  wallabag:
    template: default
    envelope: ''
    source: /wallabag-export-3-2016-07-30.json
  starthq:
    template: starthq
    envelope: items
    source: /starthq-export.json